default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: study-uploader
  username: postgres
  password: postgres

test:
  <<: *default
  database: study-uploader_test
  username: postgres
  password: postgres
