default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: study-uploader2
  username: postgres
  password: postgres

test:
  <<: *default
  database: study-uploader2_test
  username: postgres
  password: postgres
